info:
    typ: "layer1"
    source_comment: "Security.evtx"
    channel: "Security"

sendto_layer2: ActiveDirectoryComputerAccounts

events:
    4741:
        attrib_extraction: []
        short_description: "A computer account was created"
        provider_guid: "{54849625-5478-4994-a5ba-3e3b0328c30d}"
    
    4742:
        attrib_extraction: []
        short_description: "A computer account was changed"
        provider_guid: "{54849625-5478-4994-a5ba-3e3b0328c30d}"
        
    4743:
        attrib_extraction: []
        short_description: "A computer account was deleted"
        provider_guid: "{54849625-5478-4994-a5ba-3e3b0328c30d}"
