info:
    typ: "layer1"
    source_comment: "Security.evtx"
    channel: "Security"

sendto_layer2: AuditLogCleared

events:
    1102:
        attrib_extraction:
            - "userdata_flatten_first_value"
        short_description: "The audit log was cleared."
        provider_guid: "{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148}"
