info:
    typ: "layer1"
    source_comment: "Security.evtx"
    channel: "Security"

sendto_layer2: ProcessCreation

events:
    4688:
        attrib_extraction:
            - "rename_field:input_field=ProcessId,output_field=ParentProcessId"
            - "rename_field:input_field=NewProcessId,output_field=ProcessId"
            - "rename_field:input_field=NewProcessName,output_field=ProcessName"
        short_description: "A new process has been created."
        provider_guid: "{54849625-5478-4994-a5ba-3e3b0328c30d}" 

    4689:
        attrib_extraction: []
        short_description: "A process has exited."
        provider_guid: "{54849625-5478-4994-a5ba-3e3b0328c30d}" 