info:
    typ: "layer1"
    source_comment: "Security.evtx"
    channel: "Security"

sendto_layer2: ServicesUniversal

events:

    4697:
        attrib_extraction: []
        short_description: "A service was installed in the system."
        provider_guid: "{54849625-5478-4994-A5BA-3E3B0328C30D}"
  